name = "Programmer"
license = "MIT"
licenselink = "https://github.com/TanishkThoria/Hugo-Programmer/blob/main/LICENSE"
description = "A modified version of the minimal and sleek 'Hugo-Coder' theme."

homepage = "https://github.com/TanishkThoria/Hugo-Programmer"

demosite = "https://tanishkthoria.netlify.app"

tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal",
  "modified",
  "fork"
]
features = [
  "analytics",
  "favicon",
  "multilingual",
  "pagination",
  "single-column",
  "syntax-highlighting",
  "thumbnails"
]
min_version = "0.79.0"

[author]
name = "Tanishk Thoria"
homepage = "https://tanishkthoria.netlify.app"

[original]
name = "Luiz F. A. de Prá"
homepage = "https://luizdepra.com"
repo = "https://github.com/luizdepra/hugo-coder"
